### ISSUE TITLE
Unable to use vue-atlaskit

### ISSUE THREAD

**Issue by abhishekray07** [spartez/vue-atlaskit#16]
I am trying to use the package in one of my projects but I can't seem to get it to work. I followed the instructions in the README and installed and included the package like:

```
...
import atlaskit from '@spartez/vue-atlaskit';
...
Vue.use(atlaskit);
```

However, while building the application, npm throws this error:

```
in ./src/main.js

"export 'default' (imported as 'atlaskit') was not found in '@spartez/vue-atlaskit'

```

Any idea what I might be doing incorrectly?

**Comment by abilicz** [comment]
Hi!
Last week we updated rollup to new version, to enable tree shaking and we decided to drop registering the whole module since it will load many unnecessary components and increase the bundle size.
The recommended way now is to register component manually where you need it.
I will update the docs today. Sorry for that.

```js
import { Spinner } from '@spartez/vue-atlaskit';

export default {
  components: {
    Spinner
  },
};
```
